[project]
name = "task"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = ["dateparser>=1.2.2", "pydantic>=2.11.7", "typer>=0.16.0"]

[project.scripts]
task = "task_tracker.cli:app"
